### ISSUE TITLE
Ue4dumper kernel he doesn't work for me

### ISSUE THREAD

**Issue by YMY1666527646** [GoLang1337/UE4Dumper-Kernel#1]
Ue4dumper kernel he doesn't work for me
I've used the kdmapper mapping driver and it still doesn't work

**Comment by GoLang1337** [comment]
The information provided is not necessary, I can infer the problem comes from the kernel side as the process name is hard-coded, so try changing this line to the process name.

https://github.com/GoLang1337/UE4Dumper-Kernel/blob/main/Driver/memory.hpp#L211

**Comment by YMY1666527646** [comment]
> 

Thank you for your reply and help
